name: terraform

on: push

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: true
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: init
        run: terraform init
      - name: format
        run: terraform fmt
      - name: validate
        run: terraform validate
      - name: plan
        run: terraform plan
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}




